
[package]
name = "possessive"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14", features = ["dynamic_linking"] }
bevy-inspector-egui = { version = "0.24", optional = true }

[features]
default = []
inspector = ["bevy-inspector-egui"]

[profile.dev]
opt-level = 1

[profile.release]
lto = "thin"
codegen-units = 1
opt-level = "s"
